services:
  - type: web
    name: coopcontrol
    runtime: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/CourseProject-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: coopcontrol-db
          property: connectionString
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m

databases:
  - name: coopcontrol-db
    plan: free
    databaseName: coopcontrol
    user: coopcontrol
